
package com;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "H", targetNamespace = "http://com/", wsdlLocation = "http://localhost:8080/WebApplication1/H?wsdl")
public class H_Service
    extends Service
{

    private final static URL H_WSDL_LOCATION;
    private final static WebServiceException H_EXCEPTION;
    private final static QName H_QNAME = new QName("http://com/", "H");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/WebApplication1/H?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        H_WSDL_LOCATION = url;
        H_EXCEPTION = e;
    }

    public H_Service() {
        super(__getWsdlLocation(), H_QNAME);
    }

    public H_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), H_QNAME, features);
    }

    public H_Service(URL wsdlLocation) {
        super(wsdlLocation, H_QNAME);
    }

    public H_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, H_QNAME, features);
    }

    public H_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public H_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns H
     */
    @WebEndpoint(name = "HPort")
    public H getHPort() {
        return super.getPort(new QName("http://com/", "HPort"), H.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns H
     */
    @WebEndpoint(name = "HPort")
    public H getHPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://com/", "HPort"), H.class, features);
    }

    private static URL __getWsdlLocation() {
        if (H_EXCEPTION!= null) {
            throw H_EXCEPTION;
        }
        return H_WSDL_LOCATION;
    }

}
